FORMAT: 1A
HOST: http://airline.apiblueprint.org/

# AirlineReservation

This is a mock APIs project for our mid-term project.

## API [/api]

This is the entry of all our APIs.

### Welcome [GET]

+ Response 200 (text/plain)

        Welcome to our airline reservation APIs.

## Airport [/api/airports]

Provide a list of valid city in database.

### List All City [GET]

+ Response 200 (application/json)

        [
            {
                "id": "SGN",
                "name": "Ho Chi Minh City",
                "area": "Vietnam"
            },
            {
                "id": "HAN",
                "name": "Hanoi",
                "area": "Vietnam"
            },
            {
                "id": "SYD",
                "name": "Sydney",
                "area": "Australia"
            }
        ]
        
## Destinations [/api/airports/{?id}]

Provide a list of destination city from city with 'id'

+ Parameters 
    + id (string, required) - the id of the starting city.

### List Valid Destination [GET]
+ Response 200

        [
            {
                "id": "HAN",
                "name": "Hanoi",
                "area": "Vietnam"
            },
            {
                "id": "SYD",
                "name": "Sydney",
                "area": "Australia"
            }
        ]

## Passenger [/api/passenger]

Provide all customer infomation.

### List All Passenger [GET]

+ Response 200

        [
            {
                "passengeupId": "abc123",
                "passengerName": "Nguyen Văn A",
                "gender": "1",
                "dateOfBirth": "10/15/1980",
                "identifier": "263216312"
            },
            {
                "passengerId": "abc124",
                "passengerName": "Nguyen Van B",
                "gender": "1",
                "dateOfBirth": "10/15/1980",
                "identifier": "263216322"
            },
            {
                "passengerId": "abc125",
                "passengerName": "Nguyen Van C",
                "gender": "1",
                "dateOfBirth": "10/15/1980",
                "identifier": "263216352"
            }
        ]

### Add New Passenger [POST]
+ Request

        {
            "name": "Nguyen Van D",
            "gender": "1",
            "dateOfBirth": "10/15/1980",
            "identifier": "263216354"
        }

+ Response 201

        {
            "passengerId": "abc126"
        }

+ Request

        {
            "passengerId": "abc125",
            "name": "Nguyen Van C",
            "gender": "1",
            "dateOfBirth": "10/15/1980",
            "identifier": "263216352"
        }
+ Response 400

## Specified Passenger [/api/Passenger/{?id,name,identifier}]

Provide a list of customer that fit with the given criteria.

+ Parameters
    + id (string) - id of the customer
    + name (string) - name of the customer
    + identifier (number) - national id of the customer

### List Passenger with Conditions [GET]
+ Response 200

        [
            {
                "passengerId": "abc125",
                "name": "Nguyen Van C",
                "gender": "1",
                "dateOfBirth": "10/15/1980",
                "identifier": "263216352"
            }
        ]

## Flight [/api/flights]

Show all planned flight.

### List All Flight [GET]
+ Response 200

        [
            {
                "flightID": "abcdef",
                "departure": "Ho Chi Minh City",
                "arrival": "Hanoi",
                "date": "10/22/2016",
                "time": "9:00:00",
                "price": "1000000"
            }
        ]

### Add New Flight [POST]

+ Request

        {
            "departure": "Ho Chi Minh City",
            "arrival": "Hanoi",
            "date": "10/22/2016",
            "time": "12:00:00",
            "price": "1000000"
        }

+ Response 201

        {
            "flightId": "abcxyz"
        }

+ Request

        {
            "departure": "Ho Chi Minh City",
            "arrival": "Hanoi",
            "date": "10/22/2016",
            "time": "9:00:00",
            "price": "1000000"
        }
+ Response 400

## Searching Flight [/api/flights{?departure,arrival,date,number}]

Provide a list of flight.

+ Parameters
    + departure (string) - city of department
    + arrival (string) - destination
    + date (date) - date of department
    + number(number) - number of person

### List Flight with Conditions [GET]
+ Response 200

        [
            {
                "flightId": "abcdef",
                "departure": "Ho Chi Minh City",
                "arrival": "Hanoi",
                "date": "10/22/2016",
                "boardingTime": "9:00:00",
                "price": "1000000",
                "time": "1:00:00"
            }
        ]

## Seats [/api/seat/{?free,id}]

List current seat (and also their state) in flight with flight_id.

+ Parameters
    + free (boolean) - state of seats
    + id (string) - id of flight

### List Seats [GET]
+ Response 200

        [
            "flightId": "abcdef",
            "seats": [
                {
                    "seatId": "1A",
                    "class": "E",
                    "state": 1
                },
                {
                    "seatId": "1B",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "1C",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "1D",
                    "class": "E",
                    "state": 1
                },
                {
                    "seatId": "1E",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "1F",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "2A",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "2B",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "2C",
                    "class": "E",
                    "state": 1
                },
                {
                    "seatId": "2D",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "2E",
                    "class": "E",
                    "state": 0
                },
                {
                    "seatId": "2F",
                    "class": "E",
                    "state": 0
                }
            ]
        ]

## Seat Booking [/api/seat]

For booking seats. The POST method also create and return an unique Booking Identify Code.

### Book Seats [POST]

+ Request

        [
            "flightId": "abcdef",
            "seats": [
                {
                    "seatId": "15a"
                },
                {
                    "seatId": "16a"
                }
            ],
            "passengerId": "abc123"
        ]

+ Response 201

        {
            "bookingCode": "abczzz"
        }

+ Request

        [
            "flightId": "abcdef",
            "seats": [
                {
                    "seatId": "10a",
                }
            ]
        ]
+ Response 400

## Booking Infomation [/api/seat/{code}]

Return infomation about provided booking code.

+ Parameters
    + code (string) - booking identify code

### Infomation [GET]

+ Response 200

        [
            "flightId": "abcdef",
            "seats": [
                {
                    "seatId": "15a"
                },
                {
                    "seatId": "15a"
                }
            ],
            "passengerId": "abc123",
            "state": "1"
        ]